/// Categorized and ranked mindsets, ranging from -10 to 10.
/// They should appear in the dropdown from most positive to most negative.
const Map<String, Map<String, int>> MIND_SET_VALUES = {
  "Joy": {
    "Important": 10,
    "Hopeful": 9,
    "Liberated": 8,
    "Loving": 7,
    "Ecstatic": 7,
    "Satisfied": 6,
    "Trustful": 6,
    "Brave": 5,
    "Inspired": 4,
    "Respected": 4,
    "Tender": 3,
    "Amused": 3,
    "Open": 3,
    "Playful": 2,
    "Curious": 1,
    "Provocative": 0,
  },
  "Awe": {
    "Enthusiastic": 4,
    "Energetic": 4,
    "Respectful": 3,
    "Amazed": 2,
    "Confused": -1,
    "Thunderstruck": -4,
    "Shocked": -4,
    "Disappointed": -5,
  },
  "Sadness": {
    "Indifferent": 0,
    "Vulnerable": -1,
    "Bad": -2,
    "Sidelined": -3,
    "Shameful": -3,
    "Left out": -4,
    "Apathetic": -5,
    "Empty": -6,
    "Regretful": -6,
    "Guilty": -7,
    "Isolated": -9,
    "Powerless": -10,
  },
  "Disgust": {
    "Rebellious": -1,
    "Insecure": -5,
    "Judgemental": -5,
    "Disgusted": -6,
    "Disgusting": -7,
    "Hateful": -10,
  },
  "Anger": {
    "Wild": -1,
    "Embarrassed": -1,
    "Sarcastic": -2,
    "Sceptical": -2,
    "Annoyed": -3,
    "Jealous": -6,
    "Doubtful": -6,
    "Withdrawn": -6,
    "Provoked": -6,
    "Insecure": -7,
    "Furious": -7,
    "Hostile": -8,
    "Enraged": -9,
    "Neglected": -10,
    "Broken": -10,
  },
  "Fear": {
    "Foolish": -1,
    "Disrespected": -3,
    "Estranged": -5,
    "Incompetent": -6,
    "Worried": -6,
    "Startled": -7,
    "Terrified": -8,
    "Broken": -9,
    "Inadequate": -9,
    "Inferior": -9,
    "Meaningless": -10,
    "Worthless": -10,
  },
};

const HOUR_AS_MILLISECONDS = 60 * 60 * 1000;
const DAY_AS_MILLISECONDS = HOUR_AS_MILLISECONDS * 24;
const WEEK_AS_MILLISECONDS = DAY_AS_MILLISECONDS * 7;
