Map<String, Map<String, int>> MIND_SET_VALUES = {
  "Sadness": {
    "Shameful": 0,
    "Regretful": 0,
    "Guilty": 0,
    "Sidelined": 0,
    "Powerless": 0,
    "Vulnerable": 0,
    "Empty": 0,
    "Bad": 0,
    "Left out": 0,
    "Isolated": 0,
    "Apathetic": 0,
    "Indifferent": 0,
  },
  "Joy": {
    "Tender": 0,
    "Playful": 0,
    "Open": 0,
    "Inspired": 0,
    "Loving": 0,
    "Hopeful": 0,
    "Provocative": 0,
    "Brave": 0,
    "Satisfied": 0,
    "Respected": 0,
    "Trustful": 0,
    "Important": 0,
    "Curious": 0,
    "Amused": 0,
    "Ecstatic": 0,
    "Liberated": 0,
  },
  "Disgust": {
    "Disgusted": 0,
    "Insecure": 0,
    "Hateful": 0,
    "Disgusting": 0,
    "Rebellious": 0,
    "Judgemental": 0,
  },
  "Anger": {
    "Sarcastic": 0,
    "Sceptical": 0,
    "Doubtful": 0,
    "Withdrawn": 0,
    "Annoyed": 0,
    "Enraged": 0,
    "Hostile": 0,
    "Provoked": 0,
    "Wild": 0,
    "Furious": 0,
    "Broken": 0,
    "Embarrassed": 0,
    "Jealous": 0,
    "Insecure": 0,
    "Neglected": 0,
  },
  "Fear": {
    "Foolish": 0,
    "Disrespected": 0,
    "Estranged": 0,
    "Incompetent": 0,
    "Meaningless": 0,
    "Worthless": 0,
    "Inferior": 0,
    "Inadequate": 0,
    "Worried": 0,
    "Broken": 0,
    "Startled": 0,
    "Terrified": 0,
  },
  "Awe": {
    "Enthusiastic": 0,
    "Energetic": 0,
    "Respectful": 0,
    "Amazed": 0,
    "Disappointed": 0,
    "Confused": 0,
    "Thunderstruck": 0,
    "Shocked": 0,
  },
};
